#!/bin/bash
bayeselo <<ELOSCRIPT
prompt off
readpgn $1
players >__players.txt
elo
mm
cov
ratings >__ratings.txt
los >__los.txt
x
x
ELOSCRIPT
out=${1%.pgn}.bayes
echo -e "Players" > $out
cat __players.txt >> $out
echo -e "\nRatings" >> $out
cat __ratings.txt >> $out
echo -e "\nLOS" >> $out
cat __los.txt >> $out
rm __players.txt __ratings.txt __los.txt
cat $out
