#!/bin/bash
for pgn in $@; do
    readpgn="${readpgn}readpgn $pgn"$'\n'
done
bayeselo <<ELOSCRIPT
prompt off
$readpgn
players >__players.txt
elo
mm
covariance
ratings >__ratings.txt
los >__los.txt
x
x
ELOSCRIPT
rm bayes.out
out=bayes.out
echo -e "\nRating" >> $out
cat __ratings.txt >> $out
echo -e "\nLOS" >> $out
cat __los.txt >> $out
rm __players.txt __ratings.txt __los.txt
cat $out
