#!/bin/bash

extract = $HOME/src/chess/pgn-extract/pgn-extract
out=${1%.pgn}

$extract -bu19 -nremainder1.pgn $1 $out_u20.pgn
$extract -bl20 -bu29 -nremainder2.pgn remainder1.pgn $out_u30.pgn
$extract -bl30 -bu39 -nremainder3.pgn remainder2.pgn $out_u40.pgn
$extract -bl40 -bu49 -nremainder4.pgn remainder3.pgn $out_u50.pgn
$extract -bl50 -bu59 -nremainder5.pgn remainder4.pgn $out_u60.pgn
rm remainder*.pgn
